version: 0.2

env:
  variables:
    AWS_REGION: eu-west-2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 577638398727.dkr.ecr.eu-west-2.amazonaws.com

  build:
    commands:
      - echo Building backend...
      - docker build -t backend ./backend
      - docker tag backend:latest 577638398727.dkr.ecr.eu-west-2.amazonaws.com/backend:$IMAGE_TAG
      - docker tag backend:latest 577638398727.dkr.ecr.eu-west-2.amazonaws.com/backend:latest

  post_build:
    commands:
      - echo Pushing backend image...
      - docker push 577638398727.dkr.ecr.eu-west-2.amazonaws.com/backend:$IMAGE_TAG
      - docker push 577638398727.dkr.ecr.eu-west-2.amazonaws.com/backend:latest

      - echo Generating imagedefinitions file...
      - |
        echo '[{"name":"BackendContainer","imageUri":"577638398727.dkr.ecr.eu-west-2.amazonaws.com/backend:'$IMAGE_TAG'"}]' > backend-imagedefinitions.json

artifacts:
  files:
    - backend-imagedefinitions.json
